### ISSUE TITLE
Question about potential typos in error descriptions

### ISSUE THREAD

**Issue by fhightower** [Bandwidth/api-docs#1150]
Hello! I have a question about two error descriptions:

1. The description for `5610` is `submit_ sm-or-submit_ multi-failed` - is this correct?
2. The description for `5630` is `message-not-acknowle` - should this be `message-not-acknowled`?

Thanks in advanced for any input on these!

**Comment by fhightower** [comment]
@DX-Bandwidth or @ajrice6713: Any input on this? Thanks!

**Comment by ajrice6713** [comment]
Hey @fhightower - sorry we missed this, checking with the team that owns these docs now and we will get these fixed!

**Comment by fhightower** [comment]
No problem - thank you!

**Comment by fhightower** [comment]
@ajrice6713 : Thanks for looking into this. Any update?

**Comment by ckoegel** [comment]
Hey @fhightower, sorry for the delayed response, we're unfortunately still trying to get the appropriate team to update their documentation and get this resolved. Just wanted to let you know we haven't forgotten about this and are still working to try to get these docs updated. I'm going to close this and your other issue as we've moved the contents of this repo into another private repo.
